[project]
name = "bookops-sierra"
version = "0.2.0"
description = "Sierra API wrapper"
authors = [{name = "Tomasz Kalata", email = "klingaroo@gmail.com"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["requests (>=2.32.3, <3.0.0)", "types-requests (>=2.32.0.20241016, <3.0.0)"]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-cov = "^6.0.0"
black = "^24.10.0"
mypy = "^1.14.1"
flake8 = "^7.1.2"

[tool.black]
line-length = 88
target-version = ['py312', 'py313']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs
       | \.git
       | \.hg
       | \.mypy_cache
       | \.tox
       | \.venv
       | _build
       | buck-out
       | build
       | dist
    )/
    | temp.py
)
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
	"webtest: mark a test hitting live endpoints",
    "http_code: use to pass returned http code to 'mock_session_response' fixture that mocks 'requests.Session.send' method"
]
addopts = '-m "not webtest" --cov=bookops_sierra/'

[tool.coverage.run]
branch = true
relative_files = true
source = ["."]
omit = ["tests/*"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["E501", "ANN"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.3.4,<9",
    "pytest-cov>=6.0.0,<7",
    "pytest-mock>=3.14.0,<4"
]